DATA_PATH = 'data'
PROFILES_DATA_PATH = DATA_PATH + '/jammu_kashmir.json'
# PICS_DATA_PATH = 'data/bania_women_pics.json'
DP_OUTPUT_FOLDER = 'all_dp/jammu_kashmir'
SEARCH_ID = '170995222154206983'
NUM_OF_RESULTS = 260
DELAY_IN_SECONDS = 1
EXPRESSED_INTEREST_FILEPATH = 'sent_interests.txt'
AUTH_TOKEN = 'eyJhbGciOiJIUzI1NiJ9.eyJ2ZXIiOjIuMCwicGlkIjo1NDIwNjk4MywidG9rZW4iOiJERDVERHNHa0REUkNqc2thMkM4QzE1YjEzczM4RDZEayIsImF0IjoxNzExMDY1NjcyLCJhcCI6e319.jFxASPYjwLlDgFxXwDvmwxo7fORx2HqFiCVWaonUxOM'

